### PR TITLE
Fixes #41

### LINKED ISSUE #41: Incorrect behavior for ls
I noticed a few main issues with `ls` so far:

 1. `ls filedoesntexist` should output a message of the form `ls: cannot access filedoesntexist: No such file or directory`. Currently, it has no output.
 2. Calling `ls` with multiple arguments causes files to look kind of like directories. This has output like:
  ```
  cash $ ls README.md appveyor.yml src
  README.md:
  README.md

  appveyor.yml:
  appveyor.yml

  src:
  commands  delimiter.js  help  help.js  index.js  lib  preparser.js  util  windows.js
  ```

  whereas I would expect:
  ```
  cash $ ls README.md appveyor.yml src
  appveyor.yml README.md

  src:
  commands  delimiter.js  help  help.js  index.js  lib  preparser.js  util  windows.js
  ```
 3. Calling `ls` on non-existing files, if there are multiple arguments, treats them like empty directories:
  ```
  cash $ ls noexist1 noexist2
  noexist1:


  noexist2:

  ```
  whereas I would expect:
  ```
  cash $ ls noexist1 noexist2
  ls: cannot access noexist1: No such file or directory
  ls: cannot access noexist2: No such file or directory
  ```

I suspect solving bugs 1 and 2 will solve 3 for you.

All of this is running off the latest release of  `cash` on Ubuntu.

### PR DESCRIPTION
**Pull request by legien**
- Adds output where no output was given before
- Files are now only files an come first (before dirs)
- Non-existing files are not treated as directories anymore

### CODE REVIEW

File: src/commands/ls.js [hunk 1]
```diff
@@ -160,18 +196,18 @@ const ls = {
...
-            0);
+              (b.data.mtime < a.data.mtime) ? -1 :
+                  0);
         }
         // Sort alphabetically - default.
         const aFileName = fileFromPath(a.file)
-          .trim()
-          .toLowerCase()
-          .replace(/\W/g, '');
+            .trim()
```
Comment (dthree) [inline src/commands/ls.js]: Reason for four spaces? I don't think that's per the code style.

**Comment by dthree** [comment]
This looks awesome! Thanks so much!

File: src/commands/ls.js (hunk 1 above)
Comment (gghez) [inline src/commands/ls.js]: `.editorconfig` may be helpful when working on different platforms or with many people.
